#Container names are unique (using project slug)
#so they don't interfere with other project on the same machine
#Remember to not change this.
#REALLY remember this time.

version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: test-frontend-localhost
    command: ./docker/start.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
